# Generated by Django 3.2.16 on 2022-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('is_flexible', models.BooleanField(default=False)),
                ('no_of_assets', models.IntegerField()),
                ('asset_type', models.CharField(max_length=255)),
                ('asset_sensitivity', models.CharField(max_length=255)),
                ('whom_to_deliver', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('is_flexible', models.BooleanField(default=False)),
                ('no_of_assets', models.IntegerField()),
                ('travel_medium', models.CharField(max_length=255)),
                ('is_applied', models.BooleanField(default=False)),
                ('status', models.CharField(default='NOT_APPLIED', max_length=255)),
            ],
        ),
    ]
