# Generated by Django 3.2.16 on 2022-10-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterRiderMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.IntegerField()),
                ('rider_id', models.IntegerField()),
                ('is_invalid', models.BooleanField(default=False)),
            ],
        ),
    ]
